### ISSUE TITLE
No returning same results as example_files

### ISSUE THREAD

**Issue by oseias-r-junior** [simroux/Inovirus#1]
Hi simroux,

I'm trying to use your inovirus_detector with my data, but first I've applied your script to the example_file it come along with the script. But the returning files are not as the expected_results. Also, there is no gff file as output. 
Follows the output in terminal...

------------------------------------------------------------------------------------------------------------------------
Real start = 29234 --- Real end = 90649
hmmsearch -o /dev/null --noali --tblout /home/oseias/Documents/Oseias/Programs/Inovirus_detector/input/2731957639_129103.assembled_frag_Ga0128599_102362_vs_Pfam_db.tsv --cpu 2 /home/oseias/Documents/Oseias/Programs/Inovirus_detector/Pfam-A.hmm /home/oseias/Documents/Oseias/Programs/Inovirus_detector/input/2731957639_129103.assembled_frag_Ga0128599_102362_prots.faa

hmmsearch -o /dev/null --noali --tblout /home/oseias/Documents/Oseias/Programs/Inovirus_detector/input/2731957639_129103.assembled_frag_Ga0128599_102362_vs_InoSuperPCs.tsv --cpu 2 /home/oseias/Documents/Oseias/Programs/Inovirus_detector/Inovirus_detector/Inovirus_db/Superclusters_db.hmm /home/oseias/Documents/Oseias/Programs/Inovirus_detector/input/2731957639_129103.assembled_frag_Ga0128599_102362_prots.faa

blastp -query /home/oseias/Documents/Oseias/Programs/Inovirus_detector/input/2731957639_129103.assembled_frag_Ga0128599_102362_prots.faa -db /home/oseias/Documents/Oseias/Programs/Inovirus_detector/Inovirus_detector/Inovirus_db/Inoviridae_singletons -out /home/oseias/Documents/Oseias/Programs/Inovirus_detector/input/2731957639_129103.assembled_frag_Ga0128599_102362_vs_singletons.tsv -num_threads 2 -outfmt 6 -evalue 0.001

**./Predict_inovirus_coat_proteins.pl -f /home/oseias/Documents/Oseias/Programs/Inovirus_detector/input/2731957639_129103.assembled_frag_Ga0128599_102362_prots.faa -sp /home/oseias/Documents/Oseias/Programs/signalp-4.1/signalp -th /home/oseias/Documents/Oseias/Programs/tmhmm-2.0c/bin/tmhmm
Seems like there was a problem with Predict_inovirus_coat_proteins.pl -> we didn't get any output file**
------------------------------------------------------------------------------------------------------------------------
I'll be glad with any response regarding this issue.

**Comment by simroux** [comment]
Hi,

Seems like this is only the end of the output (there should be some information before the "Real start = 29234 --- Real end = 90649"). It looks however as if the last step "Predict_inovirus_coat_proteins.pl" didn't work properly. Could you try running this command line separately (from the same folder from which you originally try to run "Identify_candidate_fragments_from_gbk.pl"), i.e.:
>./Predict_inovirus_coat_proteins.pl -f /home/oseias/Documents/Oseias/Programs/Inovirus_detector/input/2731957639_129103.assembled_frag_Ga0128599_102362_prots.faa -sp /home/oseias/Documents/Oseias/Programs/signalp-4.1/signalp -th /home/oseias/Documents/Oseias/Programs/tmhmm-2.0c/bin/tmhmm

and check the output of this command specifically ?

**Comment by oseias-r-junior** [comment]
Hi simroux,

First of all, thank you very much for such a fast response to my issue.

So, I ran the code as suggested. The whole terminal output should be attached
[output_2.txt](https://github.com/simroux/Inovirus/files/3050561/output_2.txt)
Plus a file "2731957639_129103.assembled_frag_Ga0128599_102362_prots.faa_inovirus_coat_prediction.csv" was created by running the code you (and terminal script output) suggested.

Also, I must tell you that in order to running the script "Identify_candidate_fragments_from_gbk.pl" (the same I sent you the terminal output) in first place, I had to change the file input (2731957639_129103.assembled.gbk, as it came along with the inovirus_detector). It seems that one of the gene were missing. So I edit the file. I'd erased this header-ok-but-missing-sequence gene and then a step for blast finally ran. But as I sent you I still had an issue predicting inovirus coat. 

Now, it seems that running Predict_inovirus_coat_proteins.pl it was possible to detect inovirus coat from generated data (2731957639_129103.assembled_frag_Ga0128599_102362_prots.faa).

**Comment by oseias-r-junior** [comment]
Me again... I think I found one of the reasons why it was going something wrong. The tmhmm was with wrong path at the header "/local/bin/perl" instead of "/bin/perl".
I fixed and finally worked. I'm sending also the output at the terminal as it seems to be ok.
[output_1_new.txt](https://github.com/simroux/Inovirus/files/3050625/output_1_new.txt)
Thanks again simroux!

**Comment by simroux** [comment]
Sounds good, thanks for the update ! I will add this information to the Readme in case another user encounters the same issue.
