### ISSUE TITLE
Predict_inovirus_coat_proteins.pl signalp "ormat" is not a valid format

### ISSUE THREAD

**Issue by Chrisjrt** [simroux/Inovirus#2]
Hi, 

I'm trying out Inovirus detector and I'm having an issue getting the example data to run. When I run the following command:

`./Identify_candidate_fragments_from_gbk.pl -g Example_files/2731957639/2731957639_129103.assembled.gbk -p Pfam-A.hmm -sp signalp-4.1/ -th tmhmm-2.0c/bin/tmhmm -d Inovirus_db/ -t 32`

I get the error:

`./Predict_inovirus_coat_proteins.pl -f Example_files/2731957639/2731957639_129103.assembled_frag_Ga0128599_102362_prots.faa -sp signalp-4.1/ -th tmhmm-2.0c/bin/tmhmm
mv: cannot stat 'Tmp_summary.signalp5': No such file or directory
mv: cannot stat 'Tmp_mature.fasta': No such file or directory
Can't open './out_tmp_signalp_gramp' for reading: 'No such file or directory' at ./Predict_inovirus_coat_proteins.pl line 113
Seems like there was a problem with Predict_inovirus_coat_proteins.pl -> we didn't get any output file `

Having seen the that running Predict_inovirus_coat_proteins.pl was the next step to try when issue #1 had a similar problem with Predict_inovirus_coat_proteins.pl, I ran that command as so:

`./Predict_inovirus_coat_proteins.pl -f Example_files/2731957639/2731957639_129103.assembled_frag_Ga0128599_102362_prots.faa -sp signalp-4.1/ -th tmhmm-2.0c/bin/tmhmm`

Which gave me the error:

`Running SignalP5 with gram+ model
./signalp -format short -mature -org gram+ -fasta /home/chris/inovirus_test/Inovirus/Inovirus_detector/Example_files/2731957639/2731957639_129103.assembled_frag_Ga0128599_102362_prots.faa -prefix /home/chris/inovirus_test/Inovirus/Inovirus_detector/Tmp
"ormat" is not a valid format. It can be "summary" or"short" or "long" or "all"

mv Tmp_summary.signalp5 ./out_tmp_signalp_gramp
mv: cannot stat 'Tmp_summary.signalp5': No such file or directory

mv Tmp_mature.fasta ./Tmpmatured_gp.faa
mv: cannot stat 'Tmp_mature.fasta': No such file or directory

Can't open './out_tmp_signalp_gramp' for reading: 'No such file or directory' at ./Predict_inovirus_coat_proteins.pl line 113
` 

My Perl is pretty much non-existent but from the above and looking at the ./Predict_inovirus_coat_proteins.pl script, I think the -sp flag is using the run_signalp5 subroutine instead of the run_signalp subroutine (as the above error says '"ormat" is not a valid format.' for running signalp and the only place i could see 'format' in the script is in that subroutine). 

Also when I use the -sp flag with the path directly to the signalp file rather than folder I get an error saying:

`Can't chdir('signalp-4.1/signalp'): Not a directory at ./Predict_inovirus_coat_proteins.pl line 302`

And likewise the only "chdir" command I could find was in the run_signalp5 subroutine. This is also why I had the -sp path going to the signalp folder rather than file in the Identify_candidate_fragments_from_gbk.pl command.

Sorry for the long winded issue, and massive thanks for any help you can provide, and for making this tool!

**Comment by simroux** [comment]
Hi,

Sorry about that, there was a mistake in the last commit (where I added support for SignalP 5). It should be fixed in the last version I just pushed: basically you can use either signalP 4 and earlier, or signalP 5. For the latter, use the argument "sp" to point to the signalp executable. For the latter, use the argument "sp5" to point to the bin folder of signalp5. 

Let me know if it works better now ! (may have to start from a fresh output directory).

Best,
Simon

**Comment by Chrisjrt** [comment]
Hi Simon, 

Thanks for the quick reply! Yup that fixed it and I was able to run with no errors.

Thanks again!

Chris

**Comment by simroux** [comment]
Great !
